language: minimal

dist: focal

services:
  - docker

cache:
  directories:
  - "${HOME}/.build"

jobs:
  include:
    - stage: build only
      if: branch != main
      script:
        - ./build --build-num "${TRAVIS_BUILD_NUMBER}" --use-cache
        - ./build --build-num "${TRAVIS_BUILD_NUMBER}" --use-cache --noavx

    - stage: build & push
      if: branch = main
      script:
        - ./build --build-num "${TRAVIS_BUILD_NUMBER}" --use-cache
        - ./build --build-num "${TRAVIS_BUILD_NUMBER}" --use-cache --noavx
        - echo "${DOCKER_PASSWORD}" | ./push --build-num "${TRAVIS_BUILD_NUMBER}" -
        - echo "${DOCKER_PASSWORD}" | ./push --build-num "${TRAVIS_BUILD_NUMBER}" --noavx -
      after_script:
        - tail -n +1 /tmp/*.log

notifications:
  email:
    - asfedorov@gmail.com
    - k@mindsync.ai
    - yellow4x@gmail.com

