#!/bin/bash
set -e

usage() {
cat << EOF
Usage: ./"${0}" [OPTIONS]
Build Mindsync Docker Python images.

Options:
    -c, --use-cache Use layer cache when building a new image.
    --noavx         Build jupyter image with tensorflow having no AVX support.
    --tag-suffix    Tag suffix to append to target image (default: '')
EOF
}

CACHE_FLAG='--no-cache'
IMAGE_NAME='mindsync/python'
IMAGE_TAG='gpu-p37-cu11'
DOCKERFILE="Dockerfile"
TAG_SUFFIX=''

while :; do
    case "$1" in 
        --noavx)
            IMAGE_TAG='gpu-p37-cu11-noavx'
            DOCKERFILE='Dockerfile-noavx'
            ;;
        -h|--help)
            usage
            exit
            ;;
        -c|--use-cache)
            CACHE_FLAG=''
            ;;
        --tag-suffix)
            shift
            TAG_SUFFIX="-${1}"
            ;;
        -?*)
            usage
            printf 'ERROR: Unknown option: %s\n' "$1" >&2
            exit
            ;;
        *)
            break
    esac

    shift
done

readonly CACHE_FLAG
readonly IMAGE_TAG

set -x
docker build --rm --pull ${CACHE_FLAG} -t "${IMAGE_NAME}:${IMAGE_TAG}${TAG_SUFFIX}" -f "${DOCKERFILE}" .
