FROM jupyter/minimal-notebook

LABEL maintainer="Mindsync <mail@mindsync.ai>"
ARG NB_USER="jovyan"

USER root

# Copy local files as late as possible to avoid cache busting
COPY start.sh start-notebook.sh start-singleuser.sh /usr/local/bin/

# Install customizations
COPY --chown="${NB_UID}:${NB_GID}" custom /home/${NB_USER}/.jupyter/custom
COPY --chown="${NB_UID}:${NB_GID}" scripts/custom.py /usr/local/bin/custom.py
COPY --chown="${NB_UID}:${NB_GID}" scripts/mindsync.py /usr/local/bin/mindsync.py

# Currently need to have both jupyter_notebook_config and jupyter_server_config to support classic and lab
COPY jupyter_notebook_config.py /etc/jupyter/

# Prepare upgrade to JupyterLab V3.0 #1205
RUN sed -re "s/c.NotebookApp/c.ServerApp/g" \
    /etc/jupyter/jupyter_notebook_config.py > /etc/jupyter/jupyter_server_config.py && \
    fix-permissions /etc/jupyter/ && \
    chmod a+rx /usr/local/bin/custom.py \
               /usr/local/bin/mindsync.py \
               /usr/local/bin/start-notebook.sh \
               /usr/local/bin/start.sh \
               /usr/local/bin/start-singleuser.sh

RUN rm -rf /tmp/*

ARG IMAGE_NAME="undefined"
RUN echo "{\"fullName\": \"${IMAGE_NAME}\"}" > /etc/mindsync.json

USER $NB_UID

RUN rm -rf "${HOME}/.cache/*"
WORKDIR "${HOME}"

