ARG BASE_CONTAINER=jupyter/minimal-notebook
FROM $BASE_CONTAINER

LABEL maintainer="Mindsync <mail@mindsync.ai>"
ARG NB_USER="jovyan"

USER root

ADD custom /home/${NB_USER}/.jupyter/custom
ADD custom.py /usr/local/bin
ADD start-notebook.sh /usr/local/bin

RUN apt update && apt install -y cron

# Switch back to jovyan to avoid accidental container runs as root
# USER ${NB_UID}
