#!/bin/bash
set -e

usage() {
cat << EOF
Usage: "${0}" [OPTIONS] [-]
Push image to DockerHub.

Use dash to designate hub password is supplied by stdin.

Options:
    --noavx			Push the image without AVX support.
    --build-num     Build number to include into verseion number of the target image.
                    If not specified no version included (default: '')
    --build-ver     Build image version (default: 0.1)
    -h, --help      Print help message.
EOF
}

IMAGE_NAME='mindsync/python'
IMAGE_TAG='gpu-p37-cu11'
PASSWD_FROM_STDIN=0
TAG_SUFFIX=''
DEFAULT_VERSION='0.1'
BUILD_VERSION=''
BUILD_NUMBER=''

while :; do
    case "$1" in 
        -h|--help)
            usage
            exit
            ;;
        --noavx)
            IMAGE_TAG='gpu-p37-cu11-noavx'
            ;;
        --build-ver)
            shift
            BUILD_VERSION="${1}"
            ;;
        --build-num)
            shift
            BUILD_NUMBER="${1}"
            ;;
        -?*)
            usage
            printf 'ERROR: Unknown option: %s\n' "$1" >&2
            exit 1
            ;;
        -)
            PASSWD_FROM_STDIN=1
            ;;
        *)            
            break
    esac

    shift
done

set -eux

if [ -n "${BUILD_NUMBER}" ]; then
    BUILD_VERSION="${BUILD_VERSION:-${DEFAULT_VERSION}}.${BUILD_NUMBER}-"
else
    BUILD_VERSION=''
fi

DOCKER_USERNAME=${DOCKER_USERNAME:-"mindsync"}

if [ "${PASSWD_FROM_STDIN}" -eq 0 ]; then
    docker login -u "${DOCKER_USERNAME}" docker.io
else
    read PASSWD
    echo ${PASSWD} | docker login -u "${DOCKER_USERNAME}" docker.io --password-stdin
fi

docker push "${IMAGE_NAME}:${BUILD_VERSION}${IMAGE_TAG}"
